#
# Copyright © 2019 VMware, Inc. All Rights Reserved.
#
# SPDX-License-Identifier: BSD-2-Clause
#
---
- hosts: image_ingestion_service
  become: yes
  become_method: sudo
  
  roles:
    - image-ingestion-service
