#
# Copyright © 2019 VMware, Inc. All Rights Reserved.
#
# SPDX-License-Identifier: BSD-2-Clause
#
---
- name: install packages
  apt: 
    name: "{{ packages }}"
    update_cache: yes 
    state: latest
  vars:
    packages:
      - apache2
      - python3
      - python3-pip

- pip:
    name: paho-mqtt==1.5.0

- name: Add the user '{{ http_image_folder_owner }}' with the primary group of {{ http_image_folder_group }}
  user:
    name: "{{ http_image_folder_owner }}"
    state: present
    comment: IoT Admin
    group: "{{ http_image_folder_group }}"

- name: create folder to server images
  file:
    path: "{{ http_image_folder }}"
    owner: "{{ http_image_folder_owner }}"
    group: "{{ http_image_folder_group }}"
    state: directory
    mode: '0755'

- name: create folder to host the ip address update script
  file:
    path: "{{ip_address_manager_folder}}"
    owner: "{{ http_image_folder_owner }}"
    group: "{{ http_image_folder_group }}"
    state: directory
    mode: '0755'

- name: copy ip address update script to folder {{ip_address_manager_folder}}
  copy:
    src: ip-address-manager.sh
    dest: "{{ip_address_manager_folder}}"
    owner: "{{ http_image_folder_owner }}"
    group: "{{ http_image_folder_group }}"
    mode: '0744'

- name: add IP address manager unit file
  template: 
    src: ip-address-manager.service
    dest: /etc/systemd/system
  notify:
    - reload systemd

- name: add IP address manager timer file
  template: 
    src: ip-address-manager.timer
    dest: /etc/systemd/system
  notify:
    - reload systemd

- name: start IP address manager service
  service: 
    name: ip-address-manager.service
    state: started
    enabled: yes

- name: start IP address manager timer
  service: 
    name: ip-address-manager.timer
    state: started
    enabled: yes

- name: enabled mod_alias for apache2
  apache2_module: name=alias state=present

- name: apache2 listen on port {{ http_port }}
  lineinfile: 
    dest: /etc/apache2/ports.conf 
    regexp: "^Listen " 
    line: "Listen {{ http_port }}" 
    state: present
  notify:
    - restart apache2

- name: create virtual host file
  template: 
    src: virtualhost.conf
    dest: /etc/apache2/sites-available/000-default.conf
  notify:
    - restart apache2
